config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  namespace :admin do
    resources :categories
    resources :brands
    resources :products
    resources :orders, only: %i[index show destroy]
    get 'categories/index'
    get 'categories/show'
    get 'categories/edit'
    root 'products#index'

    get 'payments/:id/complete', to: "payments#complete", as: :complete_payment
    get 'payments/:id/fail', to: "payments#fail", as: :fail_payment
  end

  get 'home/index'
  root 'home#index'
  resources :home

  resources :products do
    resources :comments do
      member do
        get 'edit'
        post 'upvote'
        post 'downvote'
      end
    end
    collection do
      get 'search'
    end
  end
  
  get 'comments/edit'
  get 'carts/show'
  get 'cart', to: 'carts#show'
  delete 'cart', to: 'carts#destroy'
  post 'cart', to: 'carts#add', as: 'add_to_cart'

  resources :orders, only: %i[create]
  resources :cart_items, only: %i[create update destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true
  has_many :products, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  delegate :empty?, to: :cart_items

  def add_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(product_id: product.id)
    end
    current_item
  end


  def total
    cart_items.inject(0) { |sum, item| item.total_price + sum }
  end


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  validates_numericality_of :quantity, greater_than_or_equal_to: 1, less_than_or_equal_to: 5


  def total_price
    quantity * product.price
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: :true
  has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  acts_as_votable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  has_one :payment, dependent: :destroy
  has_one :shipment, dependent: :destroy

  enum state: { new: 1, failed: 2, completed: 3}, _prefix: :state


  def total
    order_items.inject(0) { |sum, item| item.total_price + sum }
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total_price
    product.price
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order

  include AASM

  aasm do
    state :pending, initial: true
    state :failed, :completed

    event :fail do
      transitions from: :pending, to: :failed
    end

    event :complete do
      transitions from: :pending, to: :completed
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
   include PgSearch::Model

 
  belongs_to :user, optional: true

  has_one_attached :image
  has_many :comments, dependent: :destroy

  belongs_to :category
  belongs_to :brand

  scope :filter_by_category, proc { |category_id| where(category_id: category_id) }
  scope :filter_by_brand, proc { |brand_id| where(brand_id: brand_id )}

  pg_search_scope :search_by_name, against: :name, using: { dmetaphone: {}, trigram: {}, tsearch: { prefix: true, any_word: true } }

  acts_as_votable

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy


  def main_image_path
    image.attached? ? image : 'main_image_placeholder.png'
  end


end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :products, dependent: :destroy
  has_many :comments


  acts_as_votable


  has_many :orders, dependent: :nullify


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  before_action :find_brand, only: %i[edit update destroy]

  def index
    @brands = Brand.all
  end


  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      redirect_to admin_brands_path
      flash[:notice] = "Brand was successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @brand.update(brand_params)
      redirect_to admin_brands_path
      flash[:notice] = "Brand was been updated"
    else
      flash[:notice] = "Product was not been updated"
      redirect_to :edit
    end
  end

  def destroy
    if @brand.destroy
      flash[:success] = "Brand deleted successfully"
      redirect_to admin_brands_path
    end
  end



  private
  def find_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name)
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(type)
    case type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end


  def weather_data
    @weather_data ||= WeatherApiConnector.new.weather_data
  end

  def weather_presenter
    @weather_presenter ||= WeatherPresenter.new(weather_data)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
# app/helpers/products_helper.rb
module ProductsHelper
  def render_product_image(product)
    puts "Rendering image for #{product.name}: #{product.image.attached?}" # Dodaj to
    if product.image.attached?
      image_tag product.image.variant(resize: '300x200') # Dostosuj rozmiar do swoich potrzeb
    else
      content_tag(:div, "No Image", class: "placeholder")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/brands/_form.html.erb
<%= form_with(model: @brand, url: admin_brands_path, method: "post", class: "styled-form my-4") do |form| %>

  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

        <ul>
          <% @brand.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "form-label text-white" %>
    <%= form.text_field :name, class: "form-control rounded-0 bg-dark text-white" %>
  </div>

  <div class="text-start">
    <%= form.submit "Save", class: "btn btn-primary rounded-pill" %>
  </div>
<% end %>

app/views/admin/brands/edit.html.erb
<!-- app/views/admin/categories/edit.html.erb -->
<h1>Edit Brand </h1>

<%= render 'admin/brands/form' %>

<%= link_to 'Back', admin_brands_path %>

app/views/admin/brands/index.html.erb
<h2>Brands</h2>

<%= link_to "Add Brand", new_admin_brand_path, class: "btn btn-info", id: "add-brand-button" %>

<table class="table">
  <thead class="table-dark">
  <tr>
    <th scope="col">Name</th>
    <th scope="col" class="text-end">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @brands.each do |brand| %>
    <tr>
      <td class="text-light"><%= brand.name %></td>
      <td class="text-end">
        <%= link_to "Edit", edit_admin_brand_path(brand), class: "btn btn-outline-secondary btn-sm me-2", id: "edit-product-#{brand.id}-button" %>
        <%= link_to 'Delete', admin_brand_path(brand), data: { turbo: true, turbo_method: :delete }, class: "btn btn-outline-danger btn-sm me-2" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Back', admin_root_path, class: "btn btn-secondary text-white" %>

app/views/admin/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', admin_brands_path %>