config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  namespace :admin do
    resources :categories
    resources :brands
    resources :products
    resources :orders, only: %i[index show destroy]
    get 'categories/index'
    get 'categories/show'
    get 'categories/edit'
    root 'products#index'

    get 'payments/:id/complete', to: "payments#complete", as: :complete_payment
    get 'payments/:id/fail', to: "payments#fail", as: :fail_payment
  end

  get 'home/index'
  root 'home#index'
  resources :home

  resources :products do
    resources :comments do
      member do
        get 'edit'
        post 'upvote'
        post 'downvote'
      end
    end
    collection do
      get 'search'
    end
  end
  
  get 'comments/edit'
  get 'carts/show'
  get 'cart', to: 'carts#show'
  delete 'cart', to: 'carts#destroy'
  post 'cart', to: 'carts#add', as: 'add_to_cart'

  resources :orders, only: %i[create]
  resources :cart_items, only: %i[create update destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true
  has_many :products, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  delegate :empty?, to: :cart_items

  def add_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(product_id: product.id)
    end
    current_item
  end


  def total
    cart_items.inject(0) { |sum, item| item.total_price + sum }
  end


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  validates_numericality_of :quantity, greater_than_or_equal_to: 1, less_than_or_equal_to: 5


  def total_price
    quantity * product.price
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: :true
  has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  acts_as_votable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  has_one :payment, dependent: :destroy
  has_one :shipment, dependent: :destroy

  enum state: { new: 1, failed: 2, completed: 3}, _prefix: :state


  def total
    order_items.inject(0) { |sum, item| item.total_price + sum }
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total_price
    product.price
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order

  include AASM

  aasm do
    state :pending, initial: true
    state :failed, :completed

    event :fail do
      transitions from: :pending, to: :failed
    end

    event :complete do
      transitions from: :pending, to: :completed
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
   include PgSearch::Model

 
  belongs_to :user, optional: true

  has_one_attached :image
  has_many :comments, dependent: :destroy

  belongs_to :category
  belongs_to :brand

  scope :filter_by_category, proc { |category_id| where(category_id: category_id) }
  scope :filter_by_brand, proc { |brand_id| where(brand_id: brand_id )}

  pg_search_scope :search_by_name, against: :name, using: { dmetaphone: {}, trigram: {}, tsearch: { prefix: true, any_word: true } }

  acts_as_votable

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy


  def main_image_path
    image.attached? ? image : 'main_image_placeholder.png'
  end


end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :products, dependent: :destroy
  has_many :comments


  acts_as_votable


  has_many :orders, dependent: :nullify


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
# app/helpers/products_helper.rb
module ProductsHelper
  def render_product_image(product)
    puts "Rendering image for #{product.name}: #{product.image.attached?}" # Dodaj to
    if product.image.attached?
      image_tag product.image.variant(resize: '300x200') # Dostosuj rozmiar do swoich potrzeb
    else
      content_tag(:div, "No Image", class: "placeholder")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger mb-3">
  <div class="container">
    <a class="navbar-brand" href="#">Admin Panel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'Home Store', root_path, class: 'navbar-brand' %>
    <%= render partial: 'weather/show' %>
    <div class="navbar-nav ms-auto">

      <% if admin_signed_in? %>
        <%= link_to 'Products', admin_products_path, class:"nav-link btn btn-outline-dark btn-inverse" %>
        <a class="nav-link" href="#"> <%= current_admin.email %></a>
        <%= link_to 'Edit profile', edit_admin_registration_path, class: 'nav-link' %>
        <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
        <%= render 'layouts/search' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/admin/_sidebar_admin.html.erb
<div class="list-group">
  <%= link_to 'Product', admin_products_path, class: "list-group-item list-group-item-action bg-primary text-white" %>
  <%= link_to 'Category', admin_categories_path, class: "list-group-item list-group-item-action bg-secondary text-white" %>
  <%= link_to 'Brand', admin_brands_path, class: "list-group-item list-group-item-action bg-info text-white" %>
  <%= link_to 'Orders', admin_orders_path, class: "list-group-item list-group-item-action bg-success text-white" %>
</div>

app/views/weather/_show.html.erb
<%= weather_presenter.description%>
<%= weather_presenter.location  %>
<%= weather_presenter.temperature %>
<%= image_tag weather_presenter.icon %>