config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  namespace :admin do
    resources :categories
    resources :brands
    resources :products
    resources :orders, only: %i[index show destroy]
    get 'categories/index'
    get 'categories/show'
    get 'categories/edit'
    root 'products#index'

    get 'payments/:id/complete', to: "payments#complete", as: :complete_payment
    get 'payments/:id/fail', to: "payments#fail", as: :fail_payment
  end

  get 'home/index'
  root 'home#index'
  resources :home

  resources :products do
    resources :comments do
      member do
        get 'edit'
        post 'upvote'
        post 'downvote'
      end
    end
    collection do
      get 'search'
    end
  end
  
  get 'comments/edit'
  get 'carts/show'
  get 'cart', to: 'carts#show'
  delete 'cart', to: 'carts#destroy'
  post 'cart', to: 'carts#add', as: 'add_to_cart'

  resources :orders, only: %i[create]
  resources :cart_items, only: %i[create update destroy]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true
  has_many :products, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  delegate :empty?, to: :cart_items

  def add_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = cart_items.build(product_id: product.id)
    end
    current_item
  end


  def total
    cart_items.inject(0) { |sum, item| item.total_price + sum }
  end


end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  validates_numericality_of :quantity, greater_than_or_equal_to: 1, less_than_or_equal_to: 5


  def total_price
    quantity * product.price
  end

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: :true
  has_many :products, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }

  acts_as_votable
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  has_one :payment, dependent: :destroy
  has_one :shipment, dependent: :destroy

  enum state: { new: 1, failed: 2, completed: 3}, _prefix: :state


  def total
    order_items.inject(0) { |sum, item| item.total_price + sum }
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  def total_price
    product.price
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order

  include AASM

  aasm do
    state :pending, initial: true
    state :failed, :completed

    event :fail do
      transitions from: :pending, to: :failed
    end

    event :complete do
      transitions from: :pending, to: :completed
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
   include PgSearch::Model

 
  belongs_to :user, optional: true

  has_one_attached :image
  has_many :comments, dependent: :destroy

  belongs_to :category
  belongs_to :brand

  scope :filter_by_category, proc { |category_id| where(category_id: category_id) }
  scope :filter_by_brand, proc { |brand_id| where(brand_id: brand_id )}

  pg_search_scope :search_by_name, against: :name, using: { dmetaphone: {}, trigram: {}, tsearch: { prefix: true, any_word: true } }

  acts_as_votable

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy


  def main_image_path
    image.attached? ? image : 'main_image_placeholder.png'
  end


end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :products, dependent: :destroy
  has_many :comments


  acts_as_votable


  has_many :orders, dependent: :nullify


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    unless user
      user = User.create(
        email: data['email'],
        password: Devise.friendly_token[0,20]
      )
    end
    user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :initialize_cart
  def index
    @products = Product.page(params[:page])

    @products = @products.filter_by_category(params[:category]) if params[:category].present?
    @products = @products.filter_by_brand(params[:brand]) if params[:brand].present?

    @show_sidebar = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_class(type)
    case type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end


  def weather_data
    @weather_data ||= WeatherApiConnector.new.weather_data
  end

  def weather_presenter
    @weather_presenter ||= WeatherPresenter.new(weather_data)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
# app/helpers/products_helper.rb
module ProductsHelper
  def render_product_image(product)
    puts "Rendering image for #{product.name}: #{product.image.attached?}" # Dodaj to
    if product.image.attached?
      image_tag product.image.variant(resize: '300x200') # Dostosuj rozmiar do swoich potrzeb
    else
      content_tag(:div, "No Image", class: "placeholder")
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_listing_products.html.erb
<div id="<%= dom_id product %>">
  <div class="col-md-12"> <!-- Zmiana szerokości na 12 kolumn na średnich i większych ekranach (md) -->
    <div class="card h-100">
      <%= link_to (image_tag product.image, class: "card-img-top", alt: product.name if product.image.attached?), product, data: { turbo: false } %>
      <div class="card-body">
        <h5 class="card-title"><%= product.name %></h5>
        <p class="card-text">$<%= product.price %></p>
        <% if product.user.present? %>
          <p class="card-text">User: <%= product.user.email %></p>
        <% end %>
        <div class="d-flex justify-content-between align-items-center">
          <% if user_signed_in? && current_user == product.user %>
            <span class="d-flex">
              <%= link_to edit_product_path(product), class: 'btn btn-warning btn-sm mr-2', data: { turbo: false } do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= button_to product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mr-2', data: { turbo: false } do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </span>
          <% end %>
          <%= link_to product_path(product), class: 'btn btn-info btn-sm mr-2', data: { turbo: false } do %>
            <i class="fa fa-search"></i>
          <% end %>

          <!-- Przycisk "Add to Cart" -->
          <%= button_to 'Add to Cart', add_to_cart_path(product_id: product.id), class: "btn btn-outline-secondary", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
  <br> <!-- Dodanie odstępu po elemencie -->
</div>

app/views/home/edit.html.erb
<!-- app/views/products/edit.html.erb -->

<div class="container mt-4">
  <h1 class="display-4">Edit Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Back', products_path, class: 'btn btn-secondary my-2' %>
</div>

app/views/home/index.html.erb
<div id="products">
  <%= turbo_stream_from :products %>

  <div id="infinity_scroll">
    <%= turbo_frame_tag "paginate_page_#{@products.current_page}" do %>
      <div class="row row-cols-1 row-cols-md-3 g-4 align-items-stretch">
        <%= render partial: 'home/listing_products', collection: @products, as: :product %>
      </div>
      <% if @products.next_page %>
        <%= turbo_frame_tag "paginate_page_#{@products.next_page}", src: home_index_path(page: @products.next_page), loading: 'lazy' do %>
          Loading...
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to "New book", new_product_path %>

app/views/home/new.html.erb
<!-- app/views/products/new.html.erb -->

<div class="container mt-4">
  <h1 class="display-4">New Product</h1>

  <%= render 'form', product: @product %>

  <%= link_to 'Back', products_path, class: 'btn btn-secondary my-2' %>
</div>