config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }


  namespace :admin do
    resources :categories
    resources :brands
    resources :products
    resources :orders, only: %i[index show destroy]
    get 'categories/index'
    get 'categories/show'
    get 'categories/edit'
    root 'products#index'

    get 'payments/:id/complete', to: "payments#complete", as: :complete_payment
    get 'payments/:id/fail', to: "payments#fail", as: :fail_payment
  end

  get 'home/index'
  root 'home#index'
  resources :home

  resources :products do
    resources :comments do
      member do
        get 'edit'
        post 'upvote'
        post 'downvote'
      end
    end
    collection do
      get 'search'
    end
  end
  
  get 'comments/edit'
  get 'carts/show'
  get 'cart', to: 'carts#show'
  delete 'cart', to: 'carts#destroy'
  post 'cart', to: 'carts#add', as: 'add_to_cart'

  resources :orders, only: %i[create]
  resources :cart_items, only: %i[create update destroy]

end

app/models/product.rb
class Product < ApplicationRecord
   include PgSearch::Model

 
  belongs_to :user, optional: true

  has_one_attached :image
  has_many :comments, dependent: :destroy

  belongs_to :category
  belongs_to :brand

  scope :filter_by_category, proc { |category_id| where(category_id: category_id) }
  scope :filter_by_brand, proc { |brand_id| where(brand_id: brand_id )}

  pg_search_scope :search_by_name, against: :name, using: { dmetaphone: {}, trigram: {}, tsearch: { prefix: true, any_word: true } }

  acts_as_votable

  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy


  def main_image_path
    image.attached? ? image : 'main_image_placeholder.png'
  end


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  layout 'admin'
  before_action :authenticate_admin!
  before_action :find_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
    @products = @products.filter_by_category(params[:category]) if params[:category].present?
    @products = @products.filter_by_brand(params[:brand]) if params[:brand].present?
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash[:notice] = "Product added successfully"
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @presenter = ProductPresenter.new(@product)
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def update

    if @product.update(product_params)
      flash[:notice] = "Product was successfully updated"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy

    if @product.destroy
      redirect_to admin_products_path
      flash[:notice] = "Product was been deleted"
    else
      flash[:alert] = "Something is wrong"
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :image, :brand_id, :category_id)
  end

  def find_product
    @product = Product.find(params[:id])
  end

end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb

class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_action :set_product, only: %i[show edit update destroy ]

  def show
    @comments = @product.comments.order(created_at: :desc)
    @show_sidebar = false
    @presenter = ProductPresenter.new(@product)
  end

  def search
    @products = SearchProduct.new.call(params[:q]).paginate(page: params[:page], per_page: 6)
    if @products.empty?
      flash[:notice] = 'There is no product you are looking for, please try again '
      redirect_back(fallback_location: root_path) unless @products.any?
    end
  end

  def new
    @product = Product.new
    @categories = Category.all.map{ |c| [c.name, c.id ]}
    @brands = Brand.all.map{ |b|[b.name, b.id]}
  end

  def create
    @product = current_user.products.build(product_params)
    @product.category_id = params[:category_id]
    @product.brand_id = params[:brand_id]

    if @product.save
      redirect_to product_url(@product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def edit
    @product = current_user.products.find(params[:id])
    @categories = Category.all.map{ |c|[c.name, c.id]}
    @brands = Brand.all.map{ |b|[b.name, b.id]}
  end

  def update
    @product = current_user.products.find(params[:id])
    @categories = Category.all.map{ |c|[c.name, c.id]}
    @brands = Brand.all.map{ |b|[b.name, b.id]}

    if @product.update(product_params)
      redirect_to root_path, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product = current_user.products.find(params[:id])
    @product.destroy

    redirect_to root_path, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :image, :brand, :category )
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
# app/helpers/products_helper.rb
module ProductsHelper
  def render_product_image(product)
    puts "Rendering image for #{product.name}: #{product.image.attached?}" # Dodaj to
    if product.image.attached?
      image_tag product.image.variant(resize: '300x200') # Dostosuj rozmiar do swoich potrzeb
    else
      content_tag(:div, "No Image", class: "placeholder")
    end
  end
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, @product], local: true, class: "styled-form my-4") do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% @product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "form-label text-white" %>
    <%= f.text_field :name, class: "form-control rounded-0 bg-dark text-white" %>
  </div>

  <div class="form-group">
    <%= f.label :price, class: "form-label text-white" %>
    <%= f.text_field :price, class: "form-control rounded-0 bg-dark text-white", placeholder: "Enter price in USD" %>
  </div>

  <div class="form-group">
    <%= f.label :image, class: "form-label text-white" %>
    <%= f.file_field :image, class: "form-control-file border-0 bg-success text-white" %>
  </div>

  <div class="form-group">
    <%= f.label :brand_id, class: "form-label text-white" %>
    <%= f.collection_select(:brand_id, Brand.all, :id, :name, { include_blank: true }, class: "form-control rounded-0 bg-dark text-white") %>
  </div>

  <div class="form-group">
    <%= f.label :category_id, class: "form-label text-white" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, { include_blank: true }, class: "form-control rounded-0 bg-dark text-white") %>
  </div>

  <div class="text-center">
    <%= f.submit "Create Product", class: "btn btn-success rounded-pill" %>
  </div>
<% end %>

app/views/admin/products/_sidebar.html.erb
<div class="container-fluid bg-dark">
  <div class="row">
    <div class="col-lg-3 order-lg-last">
      <nav class="nav flex-column">
        <h4 class="my-4 text-light">Categories</h4>
        <% Category.all.each do |category| %>
          <%= link_to category.name, admin_root_path(category: category.id), class: "nav-link text-light" %>
        <% end %>
      </nav>

      <nav class="nav flex-column">
        <h4 class="my-4 text-light">Brands</h4>
        <% Brand.all.each do |brand| %>
          <%= link_to brand.name, admin_root_path(brand: brand.id), class: "nav-link text-light" %>
        <% end %>
      </nav>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<h2 class="text-center text-success py-3">Edit Product</h2>

<%= render partial: 'admin/products/form' %>

app/views/admin/products/index.html.erb
<h2>Products</h2>

<%= link_to "Add Product", new_admin_product_path, class: "btn btn-info", id: "add-product-button" %>

<table class="table">
  <thead class="table-dark">
  <tr>
    <th scope="col">Img</th>
    <th scope="col">Name</th>
    <th scope="col">Price</th>
    <th scope="col">Category</th>
    <th scope="col">Brand</th>
    <th scope="col" class="text-end">Actions</th> <!-- Move text-end class here -->
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(product.main_image_path, width: "50x50", class: "mx-auto") %></td>
      <td class="text-light"><%= product.name %></td>
      <td class="text-light"><%= product.price %></td>
      <td class="text-light"><%= product.category.name %></td>
      <td class="text-light"><%= product.brand.name %></td>

      <td class="text-end"> <!-- Move text-end class here -->
        <%= link_to "Show", admin_product_path(product), class: "btn btn-outline-primary btn-sm", id: "show-product-#{product.id}-button" %>
        <%= link_to "Edit", edit_admin_product_path(product), class: "btn btn-outline-secondary btn-sm me-2", id: "edit-product-#{product.id}-button" %>
        <%= link_to "Delete", admin_product_path(product), data: { turbo: true, turbo_method: :delete }, class: "btn btn-outline-danger btn-sm me-2" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2 class="text-center text-success py-3">Your Awesome Product</h2>

<%= render partial: 'admin/products/form' %>

app/views/admin/products/show.html.erb
<!-- app/views/products/show.html.erb -->

<%= image_tag @product.image, class: "card-img-top", alt: @product.name if @product.image.attached? %>

<div class="card-body d-flex justify-content-between align-items-center">
  <div>
    <h1 class="display-4"><%= @presenter.full_title %></h1>
    <p class="lead">$<%= @product.price %></p>
    <% if @product.user.present? %>
      <p> <%= @product.user.email %></p>
    <% end %>
  </div>
  <div class="btn-group">
    <% if admin_signed_in? %>
      <%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-warning btn-sm mr-2' %>
      <%= button_to "Delete", admin_product_path(@product), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mr-2' %>
      <%= link_to 'Back', admin_root_path, class: 'btn btn-secondary btn-sm' %>
    <% end  %>
  </div>
</div>